str = "Radha Rani"

#INDEX ALWAYS STARTS WITH ZERO

print(str[0:5])
print(str[6:10])
print(str[0:])##PYTHON ASSUMES THAT WE WANT TO START FROM INDEX 0 AND END TILL THE LAST STRING THAT IS "10" IN OUR CASE
print(str[:10])#PYTHON ASSUMES THAT WE WANT TO START FROM INDEX 0 AND END TILL THE LAST STRING